server:
  port: 8201
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
#        - id: world-auth
#          uri: lb://world-auth
#          predicates:
#            - Path=/world-auth/**
#          filters:
#            - StripPrefix=1
        - id: world-admin
          uri: lb://world-admin
          predicates:
            - Path=/world-admin/**
          filters:
            - StripPrefix=1
#        - id: world-portal
#          uri: lb://world-portal
#          predicates:
#            - Path=/world-portal/**
#          filters:
#            - StripPrefix=1
#        - id: world-search
#          uri: lb://world-search
#          predicates:
#            - Path=/world-search/**
#          filters:
#            - StripPrefix=1
#        - id: world-demo
#          uri: lb://world-demo
#          predicates:
#            - Path=/world-demo/**
#          filters:
#            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8201/world-auth/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/*/v2/api-docs"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/webjars/**"
      - "/actuator/**"
      - "/world-auth/oauth/token"
      - "/world-auth/rsa/publicKey"
      - "/world-search/**"
      - "/world-portal/sso/login"
      - "/world-portal/sso/register"
      - "/world-portal/sso/getAuthCode"
      - "/world-portal/home/**"
      - "/world-portal/product/**"
      - "/world-portal/brand/**"
      - "/world-admin/user/login"
      - "/world-admin/user/register"
      - "/world-admin/minio/upload"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
